/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
    "../../packages/ui/src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#eae7e9",
        "error-container": "#ffdad6",
        "surface-tint": "#565e74",
        "on-tertiary-fixed": "#0b1c30",
        "surface-container-highest": "#e4e2e4",
        "on-tertiary-container": "#75859d",
        "inverse-on-surface": "#f3f0f2",
        "on-secondary": "#ffffff",
        "on-secondary-fixed-variant": "#005321",
        "surface-container-lowest": "#ffffff",
        "secondary": "#006e2f",
        "on-primary-container": "#7c839b",
        "on-background": "#1b1b1d",
        "primary": "#000000",
        "inverse-primary": "#bec6e0",
        "secondary-fixed-dim": "#4ae176",
        "inverse-surface": "#303032",
        "background": "#fcf8fa",
        "primary-container": "#131b2e",
        "on-error": "#ffffff",
        "outline": "#76777d",
        "on-surface-variant": "#45464d",
        "on-primary": "#ffffff",
        "tertiary-container": "#0b1c30",
        "surface-bright": "#fcf8fa",
        "surface": "#fcf8fa",
        "on-secondary-container": "#007432",
        "tertiary-fixed-dim": "#b7c8e1",
        "secondary-container": "#6bff8f",
        "on-secondary-fixed": "#002109",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#bec6e0",
        "on-primary-fixed": "#131b2e",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "surface-variant": "#e4e2e4",
        "outline-variant": "#c6c6cd",
        "primary-fixed": "#dae2fd",
        "tertiary-fixed": "#d3e4fe",
        "on-tertiary-fixed-variant": "#38485d",
        "tertiary": "#000000",
        "surface-dim": "#dcd9db",
        "on-surface": "#1b1b1d",
        "surface-container-low": "#f6f3f5",
        "surface-container": "#f0edef",
        "on-primary-fixed-variant": "#3f465c",
        "secondary-fixed": "#6bff8f",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Space Grotesk", "sans-serif"],
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
